### ISSUE TITLE
Error when compiling with pdflatex

### ISSUE THREAD

**Issue by eduardohenriquearnold** [MBradbury/warwick-thesis-template#1]
Hi, thanks for this very useful template! 

I had tried to compile this template before and it worked fine, but I've updated my MikTex version (pdflatex version 4.1) and now the compilation fails with the error: `Extra \endgroup. \begin{document}` on [this ](https://github.com/MBradbury/warwick-thesis-template/blob/master/Thesis.tex#L79) line.

I have noticed that if I remove lines 52-81 from `Header.tex` I can successfully compile. I couldn't find any obvious problem with those particular lines, so maybe it's some update to a particular package used there. Since I probably wouldn't use auto-references I opted to remove those lines. Just thought I'd share it here in case anyone else struggles with this issue.

**Comment by MBradbury** [comment]
This appears to be related to the catoptions package being broken in the latest version of MiKTeX (see https://tex.stackexchange.com/questions/565937/catoptions-menukeys-packages-compilation-error).

The solution is to add the following code to the first line of Thesis.tex until catoptions is fixed.

```latex
\RequirePackage[2020-02-02]{latexrelease}
```

Removing the code to support capitalised autoref would also work. I would still recommend using a package such as [cleveref](http://tug.ctan.org/tex-archive/macros/latex/contrib/cleveref/cleveref.pdf) to simplify in-document referencing.

**Comment by MBradbury** [comment]
I've pushed a fix to remove the \Autoref implementation and use cleveref instead.
